<?php

namespace App\Services;

use App\Models\Order;
use Stripe\Stripe;
use Stripe\StripeClient;
use Illuminate\Support\Str;

class StripeConnectService
{
    private ?string $secretKey;
    private ?string $webhookSecret;
    private bool $mockMode;
    private ?StripeClient $stripe = null;

    public function isMockMode(): bool
    {
        return $this->mockMode;
    }

    /**
     * Expose the underlying Stripe client (null when in mock mode).
     */
    public function getClient(): ?StripeClient
    {
        return $this->stripe;
    }

    /**
     * Retrieve a connected account from Stripe.
     */
    public function retrieveAccount(string $accountId): array
    {
        if ($this->mockMode || empty($this->stripe)) {
            return [
                'id' => $accountId,
                'charges_enabled' => true,
                'payouts_enabled' => true,
                'requirements' => ['currently_due' => [], 'eventually_due' => [], 'past_due' => []],
                '_mock' => true,
            ];
        }

        return $this->stripe->accounts->retrieve($accountId)->toArray();
    }

    public function confirmPaymentIntent(string $paymentIntentId, string $paymentMethodId): array
    {
        if ($this->mockMode || empty($this->stripe)) {
            return [
                'id' => $paymentIntentId,
                'status' => 'succeeded',
                'amount' => 1000,
                'currency' => 'eur',
                '_mock' => true,
            ];
        }

        $intent = $this->stripe->paymentIntents->confirm($paymentIntentId, [
            'payment_method' => $paymentMethodId,
            'return_url' => url('/payment-return/stripe'),
        ]);

        return $intent->toArray();
    }

    /**
     * Create a Stripe PaymentMethod from raw card details sent by the native app form.
     * The card data is used only during this request and is never stored or logged.
     */
    public function createPaymentMethodFromCardDetails(array $cardDetails): string
    {
        $required = ['number', 'expiry_month', 'expiry_year', 'cvc'];
        foreach ($required as $field) {
            if (empty($cardDetails[$field])) {
                throw new \InvalidArgumentException("Missing card field: {$field}");
            }
        }

        if ($this->mockMode || empty($this->stripe)) {
            return 'pm_mock_' . Str::random(16);
        }

        $paymentMethod = $this->stripe->paymentMethods->create([
            'type' => 'card',
            'card' => [
                'number' => $cardDetails['number'],
                'exp_month' => (int) $cardDetails['expiry_month'],
                'exp_year' => (int) $cardDetails['expiry_year'],
                'cvc' => $cardDetails['cvc'],
            ],
            'billing_details' => [
                'name' => $cardDetails['holder_name'] ?? null,
            ],
        ]);

        return $paymentMethod->id;
    }

    /**
     * Create a Stripe PaymentMethod from a token (tok_xxx) generated by the Flutter SDK.
     */
    public function createPaymentMethodFromToken(string $tokenId): string
    {
        if ($this->mockMode || empty($this->stripe)) {
            return 'pm_mock_' . Str::random(16);
        }

        $paymentMethod = $this->stripe->paymentMethods->create([
            'type' => 'card',
            'card' => ['token' => $tokenId],
        ]);

        return $paymentMethod->id;
    }

    public function __construct()
    {
        $config = config('services.stripe_connect');
        $this->secretKey = $config['secret_key'] ?? null;
        $this->webhookSecret = $config['webhook_secret'] ?? null;
        $this->mockMode = filter_var($config['mock_mode'] ?? true, FILTER_VALIDATE_BOOLEAN);

        if (!$this->mockMode && !empty($this->secretKey)) {
            Stripe::setApiKey($this->secretKey);
            $this->stripe = new StripeClient($this->secretKey);
        }
    }

    /**
     * Create a connected account for a partner (restaurant or delivery man).
     *
     * In test mode we create custom accounts with enough data to enable transfers.
     * In production express accounts are recommended so the partner completes onboarding.
     */
    public function createConnectedAccount(object $partner, string $type = 'express'): array
    {
        if ($this->mockMode || empty($this->stripe)) {
            return $this->mockCreateConnectedAccount($partner);
        }

        $name = $partner->f_name ?? $partner->name ?? 'Partner';
        $email = $partner->email ?? 'partner-' . $partner->id . '@nexfood.test';
        $firstName = $partner->f_name ?? explode(' ', $name)[0] ?? 'Partner';
        $lastName = $partner->l_name ?? (explode(' ', $name)[1] ?? 'Teste');
        $isTestMode = str_starts_with($this->secretKey ?? '', 'sk_test_');
        $accountType = $isTestMode ? 'custom' : $type;

        $params = [
            'type' => $accountType,
            'country' => 'PT',
            'email' => $email,
            'business_type' => 'individual',
            'capabilities' => [
                'transfers' => ['requested' => true],
            ],
            'business_profile' => [
                'name' => $name,
                'product_description' => 'Partner on 6amMart marketplace',
            ],
            'metadata' => [
                'partner_type' => $partner instanceof \App\Models\Store ? 'store' : 'delivery_man',
                'partner_id' => (string) $partner->id,
            ],
        ];

        // Custom test accounts need extra data to enable transfers immediately.
        if ($isTestMode && $accountType === 'custom') {
            $bankToken = \Stripe\Token::create([
                'bank_account' => [
                    'country' => 'PT',
                    'currency' => 'eur',
                    'account_holder_name' => $name,
                    'account_holder_type' => 'individual',
                    'account_number' => 'PT50000201231234567890154',
                ],
            ]);

            $params['external_account'] = $bankToken->id;
            $params['individual'] = [
                'first_name' => $firstName,
                'last_name' => $lastName,
                'dob' => ['day' => 1, 'month' => 1, 'year' => 1990],
                'address' => [
                    'line1' => 'Rua Teste 1',
                    'city' => 'Lisboa',
                    'postal_code' => '1000-100',
                    'country' => 'PT',
                ],
            ];
            $params['tos_acceptance'] = [
                'date' => time(),
                'ip' => request()?->ip() ?? '127.0.0.1',
            ];
        }

        $account = $this->stripe->accounts->create($params);

        return $account->toArray();
    }

    /**
     * Create an account onboarding link.
     */
    public function createAccountLink(string $accountId, string $refreshUrl, string $returnUrl): array
    {
        if ($this->mockMode || empty($this->stripe)) {
            return [
                'url' => 'https://connect.stripe.com/setup/s/mock_' . Str::random(12),
                '_mock' => true,
            ];
        }

        $link = $this->stripe->accountLinks->create([
            'account' => $accountId,
            'refresh_url' => $refreshUrl,
            'return_url' => $returnUrl,
            'type' => 'account_onboarding',
        ]);

        return $link->toArray();
    }

    /**
     * Create a PaymentIntent for the customer.
     *
     * The full amount is captured by the platform, then split via transfers.
     */
    public function createPaymentSession(Order $order, array $split): array
    {
        if ($this->mockMode || empty($this->stripe)) {
            return $this->mockCreatePaymentSession($order, $split);
        }

        $totalCents = (int) round($split['total'] * 100);

        $intent = $this->stripe->paymentIntents->create([
            'amount' => $totalCents,
            'currency' => 'eur',
            'automatic_payment_methods' => [
                'enabled' => true,
                'allow_redirects' => 'never',
            ],
            'customer' => $this->getOrCreateCustomer($order),
            'transfer_group' => 'order_' . $order->id,
            'metadata' => [
                'order_id' => (string) $order->id,
                'platform' => 'sixammart',
            ],
        ]);

        return $intent->toArray();
    }

    /**
     * Execute transfers to partners after payment is captured.
     *
     * When a source charge is provided, the transfer is tied to that charge
     * instead of the platform's available balance. This is required in test
     * mode and recommended in production to avoid "insufficient funds" errors.
     */
    public function createTransfers(Order $order, array $split, ?string $sourceTransaction = null): array
    {
        if ($this->mockMode || empty($this->stripe)) {
            return $this->mockCreateTransfers($order, $split);
        }

        $results = [];
        $transferGroup = 'order_' . $order->id;

        $store = $order->store;
        if ($store && !empty($store->stripe_account_id) && $split['store_net'] > 0) {
            $params = [
                'amount' => (int) round($split['store_net'] * 100),
                'currency' => 'eur',
                'destination' => $store->stripe_account_id,
                'transfer_group' => $transferGroup,
                'metadata' => ['order_id' => $order->id, 'type' => 'store_payout'],
            ];

            if (!empty($sourceTransaction)) {
                $params['source_transaction'] = $sourceTransaction;
            }

            $results[] = $this->stripe->transfers->create($params)->toArray();
        }

        $deliveryMan = $order->delivery_man;
        if ($deliveryMan && !empty($deliveryMan->stripe_account_id) && $split['delivery_net'] > 0) {
            $params = [
                'amount' => (int) round($split['delivery_net'] * 100),
                'currency' => 'eur',
                'destination' => $deliveryMan->stripe_account_id,
                'transfer_group' => $transferGroup,
                'metadata' => ['order_id' => $order->id, 'type' => 'delivery_payout'],
            ];

            if (!empty($sourceTransaction)) {
                $params['source_transaction'] = $sourceTransaction;
            }

            $results[] = $this->stripe->transfers->create($params)->toArray();
        }

        return $results;
    }

    /**
     * Validate incoming Stripe webhook signature.
     *
     * In mock mode any payload is accepted. In production a webhook secret
     * must be configured; otherwise webhooks are rejected for safety.
     */
    public function validateWebhook(string $payload, ?string $signature): bool
    {
        if ($this->mockMode) {
            return true;
        }

        if (empty($this->webhookSecret)) {
            \Illuminate\Support\Facades\Log::warning('Stripe webhook rejected: STRIPE_WEBHOOK_SECRET is not configured');
            return false;
        }

        if (empty($signature)) {
            return false;
        }

        try {
            \Stripe\Webhook::constructEvent($payload, $signature, $this->webhookSecret);
            return true;
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::warning('Stripe webhook signature validation failed', ['error' => $e->getMessage()]);
            return false;
        }
    }

    /**
     * Get or create a Stripe customer for the order.
     */
    private function getOrCreateCustomer(Order $order): ?string
    {
        if ($this->mockMode || empty($this->stripe)) {
            return null;
        }

        $user = $order->customer;
        if (!$user) {
            return null;
        }

        $existing = $this->stripe->customers->search([
            'query' => "email:'{$user->email}'",
        ]);

        if ($existing->count() > 0) {
            return $existing->data[0]->id;
        }

        $customer = $this->stripe->customers->create([
            'email' => $user->email,
            'name' => $user->f_name . ' ' . $user->l_name,
            'phone' => $user->phone,
        ]);

        return $customer->id;
    }

    private function mockCreateConnectedAccount(object $partner): array
    {
        return [
            'id' => 'acct_' . Str::random(14),
            'type' => 'express',
            'email' => $partner->email,
            'capabilities' => ['transfers' => 'active'],
            '_mock' => true,
        ];
    }

    private function mockCreatePaymentSession(Order $order, array $split): array
    {
        $intentId = 'pi_' . Str::random(14);
        $clientSecret = $intentId . '_secret_' . Str::random(24);

        return [
            'id' => $intentId,
            'client_secret' => $clientSecret,
            'status' => 'requires_payment_method',
            'amount' => (int) round($split['total'] * 100),
            'currency' => 'eur',
            'transfer_group' => 'order_' . $order->id,
            'metadata' => [
                'order_id' => (string) $order->id,
                'platform' => 'sixammart',
            ],
            '_mock' => true,
        ];
    }

    private function mockCreateTransfers(Order $order, array $split): array
    {
        return [
            [
                'id' => 'tr_' . Str::random(14),
                'amount' => (int) round($split['store_net'] * 100),
                'currency' => 'eur',
                'destination' => $order->store?->stripe_account_id ?? 'acct_store',
                'status' => 'paid',
                '_mock' => true,
            ],
            [
                'id' => 'tr_' . Str::random(14),
                'amount' => (int) round($split['delivery_net'] * 100),
                'currency' => 'eur',
                'destination' => $order->delivery_man?->stripe_account_id ?? 'acct_delivery',
                'status' => 'paid',
                '_mock' => true,
            ],
        ];
    }
}
